# Label Encoder

In [35]:
import pandas as pd

In [36]:
df = pd.DataFrame({"name":["Vivek","Mayank","Lucky","Sangeeta","Lucky","Monica","Priya","Arpita","Sonali","Monica","Leena","Lucky","Madhu"]})

In [37]:
df.head(10)

       name
0     Vivek
1    Mayank
2     Lucky
3  Sangeeta
4     Lucky
5    Monica
6     Priya
7    Arpita
8    Sonali
9    Monica

In [38]:
from sklearn.preprocessing import LabelEncoder

In [39]:
le = LabelEncoder()

In [41]:
le.fit_transform(df["name"])

array([9, 4, 2, 7, 2, 5, 6, 0, 8, 5, 1, 2, 3])

In [43]:
df["en_ name"] = le.fit_transform(df["name"])

In [44]:
df

        name  en_ name
0      Vivek         9
1     Mayank         4
2      Lucky         2
3   Sangeeta         7
4      Lucky         2
5     Monica         5
6      Priya         6
7     Arpita         0
8     Sonali         8
9     Monica         5
10     Leena         1
11     Lucky         2
12     Madhu         3

In [46]:
new_data = df
new_data.to_csv("Label_Encoder.csv",index=False)